-- users
INSERT INTO users (id, about, activation_code, active, background_color, birthday, color_scheme, country_code, country, email, full_name, gender, language, like_count, location, media_tweet_count, muted_direct_messages, notifications_count, mentions_count, password, password_reset_code, phone_code, phone_number, private_profile, profile_customized, profile_started, registration_date, role, followers_count, following_count, followers_requests_count, tweet_count, username, website, pinned_tweet_id, unread_messages_count, avatar, wallpaper) VALUES (1, null, null, true, 'DEFAULT', null, 'BLUE', null, null, 'user2015@gmail.com', 'Random', null, null, 4, null, 3, true, 0, 0, '$2a$08$TZekzxmq.KO2f.juYNUa4eU/ePYPx3r2MWONVjPDKOBJB4qUlhkxW', null, null, null, false, true, true, '2021-11-15 14:05:08.000000', 'USER', 1, 1, 0, 6, 'Random', null, 1, 0, 'https://perfumeweb2.s3.eu-central-1.amazonaws.com/ae83099c-885b-499a-bb6f-5e34e1b69e7d_4ec7201fd370bd9870cdb326f0511f38.jpg', 'https://perfumeweb2.s3.eu-central-1.amazonaws.com/dfc8a223-45fc-43da-8b7c-f76e2c2507cd_82ecbca14eb4999212c07257f41c70e7.jpg');
INSERT INTO users (id, about, activation_code, active, background_color, birthday, color_scheme, country_code, country, email, full_name, gender, language, like_count, location, media_tweet_count, muted_direct_messages, notifications_count, mentions_count, password, password_reset_code, phone_code, phone_number, private_profile, profile_customized, profile_started, registration_date, role, followers_count, following_count, followers_requests_count, tweet_count, username, website, pinned_tweet_id, unread_messages_count, avatar, wallpaper) VALUES (2, 'Hello twitter!', null, true, 'DIM', null, 'BLUE', 'UA', 'Ukraine', 'user2016@gmail.com', 'MrCat', 'Cat', 'Ukrainian - українська', 13, 'New York', 1, false, 0, 0, '$2a$08$TZekzxmq.KO2f.juYNUa4eU/ePYPx3r2MWONVjPDKOBJB4qUlhkxW', null, '+380', 666966623, true, false, true, '2021-08-01 23:34:32.000000', 'USER', 4, 2, 0, 4, 'Cat', 'https://www.google.com', null, 0, 'https://perfumeweb2.s3.eu-central-1.amazonaws.com/348b7dbe-3ac5-477f-8483-edc24f53091b_814370.jpg', 'https://perfumeweb2.s3.eu-central-1.amazonaws.com/d0e5b95f-acc0-47ef-b499-477f7e5a1a06_PrMnWa2z.jpg');
INSERT INTO users (id, about, activation_code, active, background_color, birthday, color_scheme, country_code, country, email, full_name, gender, language, like_count, location, media_tweet_count, muted_direct_messages, notifications_count, mentions_count, password, password_reset_code, phone_code, phone_number, private_profile, profile_customized, profile_started, registration_date, role, followers_count, following_count, followers_requests_count, tweet_count, username, website, pinned_tweet_id, unread_messages_count, avatar, wallpaper) VALUES (3, 'Hello twitter!', null, true, 'DEFAULT', null, 'BLUE', null, null, 'user2017@gmail.com', 'Kitty', null, null, 0, 'New York', 1, true, 2, 0, '$2a$08$TZekzxmq.KO2f.juYNUa4eU/ePYPx3r2MWONVjPDKOBJB4qUlhkxW', null, null, null, false, true, true, '2021-08-01 23:34:32.000000', 'USER', 0, 1, 0, 2, 'Kitty', 'https://www.google.com', null, 0, 'https://perfumeweb2.s3.eu-central-1.amazonaws.com/a7e03e7c-c05f-4e30-ba8c-2271fd0b4b43_779301.jpg', null);
INSERT INTO users (id, about, activation_code, active, background_color, birthday, color_scheme, country_code, country, email, full_name, gender, language, like_count, location, media_tweet_count, muted_direct_messages, notifications_count, mentions_count, password, password_reset_code, phone_code, phone_number, private_profile, profile_customized, profile_started, registration_date, role, followers_count, following_count, followers_requests_count, tweet_count, username, website, pinned_tweet_id, unread_messages_count, avatar, wallpaper) VALUES (4, 'Hello twitter!', null, true, 'DEFAULT', null, 'BLUE', null, null, 'user2019@gmail.com', 'JavaCat', null, null, 0, 'Java', 1, false, 1, 0, '$2a$08$TZekzxmq.KO2f.juYNUa4eU/ePYPx3r2MWONVjPDKOBJB4qUlhkxW', null, null, null, false, true, true, '2021-08-01 23:34:32.000000', 'USER', 0, 1, 0, 3, 'JavaCat', 'https://www.java.com', null, 0, 'https://perfumeweb2.s3.eu-central-1.amazonaws.com/b999d944-c9ec-4a9c-b356-db937211df5c_Ec1OBK3XsAEjVZR.png', null);
INSERT INTO users (id, about, activation_code, active, background_color, birthday, color_scheme, country_code, country, email, full_name, gender, language, like_count, location, media_tweet_count, muted_direct_messages, notifications_count, mentions_count, password, password_reset_code, phone_code, phone_number, private_profile, profile_customized, profile_started, registration_date, role, followers_count, following_count, followers_requests_count, tweet_count, username, website, pinned_tweet_id, unread_messages_count, avatar, wallpaper) VALUES (5, 'Hello twitter!', null, true, 'DEFAULT', null, 'BLUE', null, null, 'user2018@gmail.com', 'КотБегемот', null, null, 0, 'London', 1, false, 2, 0, '$2a$08$TZekzxmq.KO2f.juYNUa4eU/ePYPx3r2MWONVjPDKOBJB4qUlhkxW', null, null, null, false, true, true, '2021-08-01 23:34:32.000000', 'USER', 1, 1, 0, 2, 'Кот Бегемот', 'https://www.google.com', null, 0, 'https://perfumeweb2.s3.eu-central-1.amazonaws.com/68a7b0d5-2b0c-493e-85ff-098725c52ecc_Cl5DjoUWYAAslnd.jfif', null);
-- user_subscriptions
INSERT INTO user_subscriptions (subscriber_id, user_id) VALUES (1, 2);
INSERT INTO user_subscriptions (subscriber_id, user_id) VALUES (1, 3);
INSERT INTO user_subscriptions (subscriber_id, user_id) VALUES (1, 4);
INSERT INTO user_subscriptions (subscriber_id, user_id) VALUES (1, 5);
INSERT INTO user_subscriptions (subscriber_id, user_id) VALUES (2, 1);
INSERT INTO user_subscriptions (subscriber_id, user_id) VALUES (5, 1);
-- country_codes
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (1, 'AF', '+93', 'Afghanistan');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (2, 'AL', '+355', 'Albania');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (3, 'DZ', '+213', 'Algeria');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (4, 'AS', '+1', 'American Samoa');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (5, 'AD', '+376', 'Andorra');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (6, 'AO', '+244', 'Angola');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (7, 'AI', '+1', 'Anguilla');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (8, 'AG', '+1', 'Antigua and Barbuda');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (9, 'AR', '+54', 'Argentina');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (10, 'AM', '+374', 'Armenia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (11, 'AW', '+297', 'Aruba');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (12, 'AU', '+61', 'Australia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (13, 'AT', '+43', 'Austria');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (14, 'AZ', '+994', 'Azerbaijan');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (15, 'BS', '+1', 'Bahamas');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (16, 'BH', '+973', 'Bahrain');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (17, 'BD', '+880', 'Bangladesh');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (18, 'BB', '+1', 'Barbados');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (19, 'BY', '+375', 'Belarus');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (20, 'BE', '+32', 'Belgium');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (21, 'BZ', '+501', 'Belize');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (22, 'BJ', '+229', 'Benin');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (23, 'BM', '+1', 'Bermuda');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (24, 'BT', '+975', 'Bhutan');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (25, 'BO', '+591', 'Bolivia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (26, 'BQ', '+599', 'Bonaire, Sint Eustatius and Saba');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (27, 'BA', '+387', 'Bosnia and Herzegovina');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (28, 'BW', '+267', 'Botswana');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (29, 'BR', '+55', 'Brazil');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (30, 'VG', '+1', 'British Virgin Islands');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (31, 'BN', '+673', 'Brunei');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (32, 'BG', '+359', 'Bulgaria');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (33, 'BF', '+226', 'Burkina Faso');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (34, 'BI', '+257', 'Burundi');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (35, 'KH', '+855', 'Cambodia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (36, 'CM', '+237', 'Cameroon');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (37, 'CA', '+1', 'Canada');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (38, 'CV', '+238', 'Cape Verde');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (39, 'KY', '+1', 'Cayman Islands');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (40, 'CF', '+236', 'Central African Republic');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (41, 'TD', '+235', 'Chad');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (42, 'CL', '+56', 'Chile');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (43, 'CN', '+86', 'China');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (44, 'CO', '+57', 'Colombia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (45, 'KM', '+269', 'Comoros');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (46, 'CG', '+242', 'Congo');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (47, 'CK', '+682', 'Cook Islands');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (48, 'CR', '+506', 'Costa Rica');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (49, 'HR', '+385', 'Croatia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (50, 'CU', '+53', 'Cuba');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (51, 'CW', '+599', 'Curaçao');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (52, 'CY', '+357', 'Cyprus');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (53, 'CZ', '+420', 'Czech Republic');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (54, 'CI', '+225', 'Côte dIvoire');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (55, 'DK', '+45', 'Denmark');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (56, 'DJ', '+253', 'Djibouti');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (57, 'DM', '+1', 'Dominica');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (58, 'DO', '+1', 'Dominican Republic');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (59, 'EC', '+593', 'Ecuador');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (60, 'EG', '+20', 'Egypt');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (61, 'SV', '+503', 'El Salvador');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (62, 'GQ', '+240', 'Equatorial Guinea');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (63, 'ER', '+291', 'Eritrea');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (64, 'EE', '+372', 'Estonia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (65, 'ET', '+251', 'Ethiopia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (66, 'FK', '+500', 'Falkland Islands');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (67, 'FO', '+298', 'Faroe Islands');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (68, 'FJ', '+679', 'Fiji');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (69, 'FI', '+358', 'Finland');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (70, 'FR', '+33', 'France');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (71, 'GF', '+594', 'French Guiana');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (72, 'PF', '+689', 'French Polynesia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (73, 'GA', '+241', 'Gabon');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (74, 'GM', '+220', 'Gambia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (75, 'GE', '+995', 'Georgia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (76, 'DE', '+49', 'Germany');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (77, 'GH', '+233', 'Ghana');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (78, 'GI', '+350', 'Gibraltar');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (79, 'GR', '+30', 'Greece');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (80, 'GL', '+299', 'Greenland');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (81, 'GD', '+1', 'Grenada');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (82, 'GP', '+590', 'Guadeloupe');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (83, 'GU', '+1', 'Guam');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (84, 'GT', '+502', 'Guatemala');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (85, 'GN', '+224', 'Guinea');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (86, 'GW', '+245', 'Guinea-Bissau');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (87, 'GY', '+592', 'Guyana');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (88, 'HT', '+509', 'Haiti');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (89, 'HN', '+504', 'Honduras');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (90, 'HK', '+852', 'Hong Kong');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (91, 'HU', '+36', 'Hungary');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (92, 'IS', '+354', 'Iceland');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (93, 'IN', '+91', 'India');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (94, 'ID', '+62', 'Indonesia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (95, 'IR', '+98', 'Iran');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (96, 'IQ', '+964', 'Iraq');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (97, 'IE', '+353', 'Ireland');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (98, 'IM', '+44', 'Isle Of Man');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (99, 'IL', '+972', 'Israel');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (100, 'IT', '+39', 'Italy');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (101, 'JM', '+1', 'Jamaica');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (102, 'JP', '+81', 'Japan');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (103, 'JE', '+44', 'Jersey');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (104, 'JO', '+962', 'Jordan');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (105, 'KZ', '+7', 'Kazakhstan');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (106, 'KE', '+254', 'Kenya');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (107, 'KI', '+686', 'Kiribati');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (108, 'KW', '+965', 'Kuwait');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (109, 'KG', '+996', 'Kyrgyzstan');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (110, 'LA', '+856', 'Laos');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (111, 'LV', '+371', 'Latvia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (112, 'LB', '+961', 'Lebanon');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (113, 'LS', '+266', 'Lesotho');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (114, 'LR', '+231', 'Liberia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (115, 'LY', '+218', 'Libya');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (116, 'LI', '+423', 'Liechtenstein');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (117, 'LT', '+370', 'Lithuania');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (118, 'LU', '+352', 'Luxembourg');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (119, 'MO', '+853', 'Macao');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (120, 'MK', '+389', 'Macedonia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (121, 'MG', '+261', 'Madagascar');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (122, 'MW', '+265', 'Malawi');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (123, 'MY', '+60', 'Malaysia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (124, 'MV', '+960', 'Maldives');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (125, 'ML', '+223', 'Mali');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (126, 'MT', '+356', 'Malta');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (127, 'MQ', '+596', 'Martinique');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (128, 'MR', '+222', 'Mauritania');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (129, 'MU', '+230', 'Mauritius');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (130, 'YT', '+262', 'Mayotte');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (131, 'MX', '+52', 'Mexico');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (132, 'FM', '+691', 'Micronesia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (133, 'MD', '+373', 'Moldova');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (134, 'MC', '+377', 'Monaco');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (135, 'MN', '+976', 'Mongolia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (136, 'ME', '+382', 'Montenegro');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (137, 'MS', '+1', 'Montserrat');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (138, 'MA', '+212', 'Morocco');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (139, 'MZ', '+258', 'Mozambique');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (140, 'MM', '+95', 'Myanmar');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (141, 'NA', '+264', 'Namibia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (142, 'NR', '+674', 'Nauru');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (143, 'NP', '+977', 'Nepal');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (144, 'NL', '+31', 'Netherlands');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (145, 'NC', '+687', 'New Caledonia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (146, 'NZ', '+64', 'New Zealand');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (147, 'NI', '+505', 'Nicaragua');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (148, 'NE', '+227', 'Niger');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (149, 'NG', '+234', 'Nigeria');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (150, 'NF', '+672', 'Norfolk Island');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (151, 'MP', '+1', 'Northern Mariana Islands');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (152, 'NO', '+47', 'Norway');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (153, 'OM', '+968', 'Oman');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (154, 'PK', '+92', 'Pakistan');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (155, 'PS', '+970', 'Palestine');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (156, 'PA', '+507', 'Panama');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (157, 'PG', '+675', 'Papua New Guinea');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (158, 'PY', '+595', 'Paraguay');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (159, 'PE', '+51', 'Peru');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (160, 'PH', '+63', 'Philippines');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (161, 'PL', '+48', 'Poland');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (162, 'PT', '+351', 'Portugal');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (163, 'PR', '+1', 'Puerto Rico');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (164, 'QA', '+974', 'Qatar');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (165, 'RE', '+262', 'Reunion');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (166, 'RO', '+40', 'Romania');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (168, 'RW', '+250', 'Rwanda');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (169, 'KN', '+1', 'Saint Kitts And Nevis');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (170, 'LC', '+1', 'Saint Lucia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (171, 'MF', '+590', 'Saint Martin');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (172, 'VC', '+1', 'Saint Vincent And The Grenadines');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (173, 'WS', '+685', 'Samoa');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (174, 'SM', '+378', 'San Marino');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (175, 'ST', '+239', 'Sao Tome And Principe');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (176, 'SA', '+966', 'Saudi Arabia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (177, 'SN', '+221', 'Senegal');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (178, 'RS', '+381', 'Serbia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (179, 'SC', '+248', 'Seychelles');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (180, 'SL', '+232', 'Sierra Leone');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (181, 'SG', '+65', 'Singapore');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (182, 'SX', '+1', 'Sint Maarten (Dutch part)');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (183, 'SK', '+421', 'Slovakia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (184, 'SI', '+386', 'Slovenia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (185, 'SB', '+677', 'Solomon Islands');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (186, 'SO', '+252', 'Somalia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (187, 'ZA', '+27', 'South Africa');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (188, 'KR', '+82', 'South Korea');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (189, 'SS', '+211', 'South Sudan');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (190, 'ES', '+34', 'Spain');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (191, 'LK', '+94', 'Sri Lanka');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (192, 'SR', '+597', 'Suriname');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (193, 'SZ', '+268', 'Swaziland');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (194, 'SE', '+46', 'Sweden');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (195, 'CH', '+41', 'Switzerland');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (196, 'TW', '+886', 'Taiwan');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (197, 'TJ', '+992', 'Tajikistan');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (198, 'TZ', '+255', 'Tanzania');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (199, 'TH', '+66', 'Thailand');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (200, 'CD', '+243', 'The Democratic Republic Of Congo');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (201, 'TL', '+670', 'Timor-Leste');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (202, 'TG', '+228', 'Togo');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (203, 'TO', '+676', 'Tonga');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (204, 'TT', '+1', 'Trinidad and Tobago');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (205, 'TN', '+216', 'Tunisia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (206, 'TR', '+90', 'Turkey');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (207, 'TM', '+993', 'Turkmenistan');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (208, 'TC', '+1', 'Turks And Caicos Islands');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (209, 'TV', '+688', 'Tuvalu');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (210, 'VI', '+1', 'U.S. Virgin Islands');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (211, 'UG', '+256', 'Uganda');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (212, 'UA', '+380', 'Ukraine');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (213, 'AE', '+971', 'United Arab Emirates');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (214, 'GB', '+44', 'United Kingdom');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (215, 'US', '+1', 'United States');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (216, 'UY', '+598', 'Uruguay');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (217, 'UZ', '+998', 'Uzbekistan');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (218, 'VU', '+678', 'Vanuatu');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (219, 'VE', '+58', 'Venezuela');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (220, 'VN', '+84', 'Vietnam');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (221, 'XK', '+383', 'XK');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (222, 'YE', '+967', 'Yemen');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (223, 'ZM', '+260', 'Zambia');
INSERT INTO country_codes (id, country_code, phone_code, country) VALUES (224, 'ZW', '+263', 'Zimbabwe');
-- languages
INSERT INTO languages (id, language) VALUES (1, 'Arabic - العربية');
INSERT INTO languages (id, language) VALUES (2,	'Arabic (Feminine) - العربية (مؤنث)');
INSERT INTO languages (id, language) VALUES (3,	'Bangla - বাংলা');
INSERT INTO languages (id, language) VALUES (4,	'Basque (beta) - euskara');
INSERT INTO languages (id, language) VALUES (5,	'British English');
INSERT INTO languages (id, language) VALUES (6,	'Bulgarian - български');
INSERT INTO languages (id, language) VALUES (7,	'Catalan - català');
INSERT INTO languages (id, language) VALUES (8,	'Croatian - hrvatski');
INSERT INTO languages (id, language) VALUES (9,	'Czech - čeština');
INSERT INTO languages (id, language) VALUES (10, 'Danish - dansk');
INSERT INTO languages (id, language) VALUES (11, 'Dutch - Nederlands');
INSERT INTO languages (id, language) VALUES (12, 'English');
INSERT INTO languages (id, language) VALUES (13, 'Filipino');
INSERT INTO languages (id, language) VALUES (14, 'Finnish - suomi');
INSERT INTO languages (id, language) VALUES (15, 'French - français');
INSERT INTO languages (id, language) VALUES (16, 'Galician (beta) - galego');
INSERT INTO languages (id, language) VALUES (17, 'German - Deutsch');
INSERT INTO languages (id, language) VALUES (18, 'Greek - Ελληνικά');
INSERT INTO languages (id, language) VALUES (19, 'Gujarati - ગુજરાતી');
INSERT INTO languages (id, language) VALUES (20, 'Hebrew - עברית');
INSERT INTO languages (id, language) VALUES (21, 'Hindi - हिन्दी');
INSERT INTO languages (id, language) VALUES (22, 'Hungarian - magyar');
INSERT INTO languages (id, language) VALUES (23, 'Indonesian - Indonesia');
INSERT INTO languages (id, language) VALUES (24, 'Irish (beta) - Gaeilge');
INSERT INTO languages (id, language) VALUES (25, 'Italian - italiano');
INSERT INTO languages (id, language) VALUES (26, 'Japanese - 日本語');
INSERT INTO languages (id, language) VALUES (27, 'Kannada - ಕನ್ನಡ');
INSERT INTO languages (id, language) VALUES (28, 'Korean - 한국어');
INSERT INTO languages (id, language) VALUES (29, 'Malay - Melayu');
INSERT INTO languages (id, language) VALUES (30, 'Marathi - मराठी');
INSERT INTO languages (id, language) VALUES (31, 'Norwegian - norsk');
INSERT INTO languages (id, language) VALUES (32, 'Persian - فارسی');
INSERT INTO languages (id, language) VALUES (33, 'Polish - polski');
INSERT INTO languages (id, language) VALUES (34, 'Portuguese - português');
INSERT INTO languages (id, language) VALUES (35, 'Romanian - română');
INSERT INTO languages (id, language) VALUES (36, 'Russian - русский');
INSERT INTO languages (id, language) VALUES (37, 'Serbian - српски');
INSERT INTO languages (id, language) VALUES (38, 'Simplified Chinese - 简体中文');
INSERT INTO languages (id, language) VALUES (39, 'Slovak - slovenčina');
INSERT INTO languages (id, language) VALUES (40, 'Spanish - español');
INSERT INTO languages (id, language) VALUES (41, 'Swedish - svenska');
INSERT INTO languages (id, language) VALUES (42, 'Tamil - தமிழ்');
INSERT INTO languages (id, language) VALUES (43, 'Thai - ไทย');
INSERT INTO languages (id, language) VALUES (44, 'Traditional Chinese - 繁體中文');
INSERT INTO languages (id, language) VALUES (45, 'Turkish - Türkçe');
INSERT INTO languages (id, language) VALUES (46, 'Ukrainian - українська');
INSERT INTO languages (id, language) VALUES (47, 'Urdu (beta) - اردو');
INSERT INTO languages (id, language) VALUES (48, 'Vietnamese - Tiếng Việt');
