-- users
INSERT INTO "user-test".public.users (id, about, activation_code, active, birthday, email, full_name, location, notifications_count, mentions_count, password, password_reset_code, profile_customized, profile_started, registration_date, role, tweet_count, username, website, like_count, media_tweet_count, country, gender, language, muted_direct_messages, phone, private_profile, country_code, background_color, color_scheme, pinned_tweet_id, unread_messages_count, avatar, wallpaper) VALUES (1, 'Hello2', null, true, null, 'merikbest2015@gmail.com', 'John_Doe', 'Kyiv', 0, 0, '$2a$08$1D3LToUL9ccJYqGDZNPH8uvTBwVFou5MobYvtgAakra6WdACQZWJK', null, true, true, '2021-08-01 23:34:32.000000', 'USER', 126, 'John_Doe', 'https://www.google.com', 40, 44, 'UA', 'Cat', 'Ukrainian - українська', true, 666966623, false, 'UA', 'DEFAULT', 'BLUE', null, 1, 'https://twitterclonestorage.s3.eu-central-1.amazonaws.com/ae83099c-885b-499a-bb6f-5e34e1b69e7d_4ec7201fd370bd9870cdb326f0511f38.jpg', 'https://twitterclonestorage.s3.eu-central-1.amazonaws.com/dfc8a223-45fc-43da-8b7c-f76e2c2507cd_82ecbca14eb4999212c07257f41c70e7.jpg');
INSERT INTO "user-test".public.users (id, about, activation_code, active, birthday, email, full_name, location, notifications_count, mentions_count, password, password_reset_code, profile_customized, profile_started, registration_date, role, tweet_count, username, website, like_count, media_tweet_count, country, gender, language, muted_direct_messages, phone, private_profile, country_code, background_color, color_scheme, pinned_tweet_id, unread_messages_count, avatar, wallpaper) VALUES (2, 'Hello twitter!', null, true, 'Mar 10, 1991', 'test2015@test.test', 'MrCat', 'New York', 3, 0, '$2a$08$1D3LToUL9ccJYqGDZNPH8uvTBwVFou5MobYvtgAakra6WdACQZWJK', null, true, true, '2021-08-01 23:34:32.000000', 'USER', 126, 'MrCat', 'https://www.google.com', 40, 44, 'UA', 'Cat', 'Ukrainian - українська', true, 666966623, false, 'UA', 'DEFAULT', 'BLUE', 40, 1, 'https://twitterclonestorage.s3.eu-central-1.amazonaws.com/348b7dbe-3ac5-477f-8483-edc24f53091b_814370.jpg', 'https://twitterclonestorage.s3.eu-central-1.amazonaws.com/d0e5b95f-acc0-47ef-b499-477f7e5a1a06_PrMnWa2z.jpg');
INSERT INTO "user-test".public.users (id, about, activation_code, active, birthday, email, full_name, location, notifications_count, mentions_count, password, password_reset_code, profile_customized, profile_started, registration_date, role, tweet_count, username, website, like_count, media_tweet_count, country, gender, language, muted_direct_messages, phone, private_profile, country_code, background_color, color_scheme, pinned_tweet_id, unread_messages_count, avatar, wallpaper) VALUES (3, 'Hello twitter!', '1234567890', true, 'Mar 10, 1991', 'test2016@test.test', 'MrCat', 'New York', 3, 0, '$2a$08$1D3LToUL9ccJYqGDZNPH8uvTBwVFou5MobYvtgAakra6WdACQZWJK', '1234567890', true, true, '2021-08-01 23:34:32.000000', 'USER', 126, 'MrCat', 'https://www.google.com', 40, 44, 'UA', 'Cat', 'Ukrainian - українська', true, 666966623, true, 'UA', 'DEFAULT', 'BLUE', null, 0, 'https://twitterclonestorage.s3.eu-central-1.amazonaws.com/348b7dbe-3ac5-477f-8483-edc24f53091b_814370.jpg', 'https://twitterclonestorage.s3.eu-central-1.amazonaws.com/d0e5b95f-acc0-47ef-b499-477f7e5a1a06_PrMnWa2z.jpg');
INSERT INTO "user-test".public.users (id, about, activation_code, active, birthday, email, full_name, location, notifications_count, mentions_count, password, password_reset_code, profile_customized, profile_started, registration_date, role, tweet_count, username, website, like_count, media_tweet_count, country, gender, language, muted_direct_messages, phone, private_profile, country_code, background_color, color_scheme, pinned_tweet_id, unread_messages_count, avatar, wallpaper) VALUES (4, 'Hello twitter!', null, true, 'Mar 10, 1991', 'test2017@test.test', 'MrCat', 'New York', 3, 0, '$2a$08$1D3LToUL9ccJYqGDZNPH8uvTBwVFou5MobYvtgAakra6WdACQZWJK', null, true, true, '2021-08-01 23:34:32.000000', 'USER', 126, 'MrCat', 'https://www.google.com', 40, 44, 'UA', 'Cat', 'Ukrainian - українська', true, 666966623, true, 'UA', 'DEFAULT', 'BLUE', null, 0, 'https://twitterclonestorage.s3.eu-central-1.amazonaws.com/348b7dbe-3ac5-477f-8483-edc24f53091b_814370.jpg', 'https://twitterclonestorage.s3.eu-central-1.amazonaws.com/d0e5b95f-acc0-47ef-b499-477f7e5a1a06_PrMnWa2z.jpg');
INSERT INTO "user-test".public.users (id, about, activation_code, active, birthday, email, full_name, location, notifications_count, mentions_count, password, password_reset_code, profile_customized, profile_started, registration_date, role, tweet_count, username, website, like_count, media_tweet_count, country, gender, language, muted_direct_messages, phone, private_profile, country_code, background_color, color_scheme, pinned_tweet_id, unread_messages_count, avatar, wallpaper) VALUES (5, 'Hello twitter!', null, true, 'Mar 10, 1991', 'test2018@test.test', 'MrCat', 'New York', 3, 0, '$2a$08$1D3LToUL9ccJYqGDZNPH8uvTBwVFou5MobYvtgAakra6WdACQZWJK', null, true, true, '2021-08-01 23:34:32.000000', 'USER', 126, 'MrCat', 'https://www.google.com', 40, 44, 'UA', 'Cat', 'Ukrainian - українська', true, 666966623, true, 'UA', 'DEFAULT', 'BLUE', null, 0, 'https://twitterclonestorage.s3.eu-central-1.amazonaws.com/348b7dbe-3ac5-477f-8483-edc24f53091b_814370.jpg', 'https://twitterclonestorage.s3.eu-central-1.amazonaws.com/d0e5b95f-acc0-47ef-b499-477f7e5a1a06_PrMnWa2z.jpg');
INSERT INTO "user-test".public.users (id, about, activation_code, active, birthday, email, full_name, location, notifications_count, mentions_count, password, password_reset_code, profile_customized, profile_started, registration_date, role, tweet_count, username, website, like_count, media_tweet_count, country, gender, language, muted_direct_messages, phone, private_profile, country_code, background_color, color_scheme, pinned_tweet_id, unread_messages_count, avatar, wallpaper) VALUES (6, 'Hello twitter!', null, true, 'Mar 10, 1991', 'test2019@test.test', 'MrCat', 'New York', 3, 0, '$2a$08$1D3LToUL9ccJYqGDZNPH8uvTBwVFou5MobYvtgAakra6WdACQZWJK', null, true, true, '2021-08-01 23:34:32.000000', 'USER', 126, 'MrCat', 'https://www.google.com', 40, 44, 'UA', 'Cat', 'Ukrainian - українська', true, 666966623, false, 'UA', 'DEFAULT', 'BLUE', null, 0, 'https://twitterclonestorage.s3.eu-central-1.amazonaws.com/348b7dbe-3ac5-477f-8483-edc24f53091b_814370.jpg', 'https://twitterclonestorage.s3.eu-central-1.amazonaws.com/d0e5b95f-acc0-47ef-b499-477f7e5a1a06_PrMnWa2z.jpg');
INSERT INTO "user-test".public.users (id, about, activation_code, active, birthday, email, full_name, location, notifications_count, mentions_count, password, password_reset_code, profile_customized, profile_started, registration_date, role, tweet_count, username, website, like_count, media_tweet_count, country, gender, language, muted_direct_messages, phone, private_profile, country_code, background_color, color_scheme, pinned_tweet_id, unread_messages_count, avatar, wallpaper) VALUES (7, 'Hello twitter!', null, true, 'Mar 10, 1991', 'test2020@test.test', 'MrCat', 'New York', 3, 0, '$2a$08$1D3LToUL9ccJYqGDZNPH8uvTBwVFou5MobYvtgAakra6WdACQZWJK', null, true, true, '2021-08-01 23:34:32.000000', 'USER', 126, 'MrCat', 'https://www.google.com', 40, 44, 'UA', 'Cat', 'Ukrainian - українська', true, 666966623, false, 'UA', 'DEFAULT', 'BLUE', null, 0, 'https://twitterclonestorage.s3.eu-central-1.amazonaws.com/348b7dbe-3ac5-477f-8483-edc24f53091b_814370.jpg', 'https://twitterclonestorage.s3.eu-central-1.amazonaws.com/d0e5b95f-acc0-47ef-b499-477f7e5a1a06_PrMnWa2z.jpg');

-- user_subscriptions
INSERT INTO "user-test".public.user_subscriptions (subscriber_id, user_id) VALUES (1, 2);
INSERT INTO "user-test".public.user_subscriptions (subscriber_id, user_id) VALUES (2, 1);
INSERT INTO "user-test".public.user_subscriptions (subscriber_id, user_id) VALUES (4, 2);
INSERT INTO "user-test".public.user_subscriptions (subscriber_id, user_id) VALUES (4, 1);

-- user_follower_requests
INSERT INTO "user-test".public.user_follower_requests (user_id, follower_id) VALUES (3, 1);
INSERT INTO "user-test".public.user_follower_requests (user_id, follower_id) VALUES (3, 2);
INSERT INTO "user-test".public.user_follower_requests (user_id, follower_id) VALUES (5, 2);
INSERT INTO "user-test".public.user_follower_requests (user_id, follower_id) VALUES (2, 7);

-- user_blocked
INSERT INTO "user-test".public.user_blocked (user_id, blocked_user_id) VALUES (2, 4);
INSERT INTO "user-test".public.user_blocked (user_id, blocked_user_id) VALUES (5, 2);
INSERT INTO "user-test".public.user_blocked (user_id, blocked_user_id) VALUES (6, 2);

-- user_muted
INSERT INTO "user-test".public.user_muted (user_id, muted_user_id) VALUES (2, 1);

-- subscribers
INSERT INTO "user-test".public.subscribers (user_id, subscriber_id) VALUES (2, 1);
